version: '3.8'
services:
  stats-server:
    restart: on-failure
    build: ./stats/stats-server
    image: stats-server-image
    container_name: ewm-stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:15.1-alpine
    container_name: EWM-stats-db
    ports:
      - "6541:5432"
    volumes:
      - /EWM-stats-db
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-main-service
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DB_NAME=ewm-server
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - STAT_SERVER_URL=http://ewm-stat:9090

  ewm-db:
    image: postgres:15.1-alpine
    container_name: EWM-server-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-server
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - /EWM-server-db